ansible_connection: network_cli
ansible_network_os: asa
ansible_user: admin
ansible_password: admin
ansible_become: yes
ansible_become_method: enable
ansible_become_password: admin
ansible_network_cli_ssh_type: libssh


