all:
  children:
    eos:
      hosts:
        SP1:
          ansible_host: 10.0.0.11
        SP2:
          ansible_host: 10.0.0.12
        LF1:
          ansible_host: 10.0.0.13
        LF2:
          ansible_host: 10.0.0.14
        BLF1:
          ansible_host: 10.0.0.21
        BLF2:
          ansible_host: 10.0.0.22

    asa:
      hosts:
        ASAv1:
          ansible_host: 10.0.0.31
        ASAv2:
          ansible_host: 10.0.0.32
